/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 59
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 27
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_function = 1,
  anon_sym_LPAREN = 2,
  anon_sym_COMMA = 3,
  anon_sym_RPAREN = 4,
  anon_sym_EQ = 5,
  sym_expression = 6,
  anon_sym_CR = 7,
  anon_sym_LF = 8,
  sym_name = 9,
  anon_sym_s64 = 10,
  anon_sym_f64 = 11,
  sym_comment = 12,
  sym_source_file = 13,
  sym__statement = 14,
  sym_function_definition = 15,
  sym_parameter_list = 16,
  sym_result_list = 17,
  sym_type_list = 18,
  sym_variable_declaration = 19,
  sym_variable_assignment = 20,
  sym_newline = 21,
  sym_type = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym_parameter_list_repeat1 = 24,
  aux_sym_type_list_repeat1 = 25,
  aux_sym_variable_assignment_repeat1 = 26,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_function] = "function",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [sym_expression] = "expression",
  [anon_sym_CR] = "\r",
  [anon_sym_LF] = "\n",
  [sym_name] = "name",
  [anon_sym_s64] = "s64",
  [anon_sym_f64] = "f64",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_function_definition] = "function_definition",
  [sym_parameter_list] = "parameter_list",
  [sym_result_list] = "result_list",
  [sym_type_list] = "type_list",
  [sym_variable_declaration] = "variable_declaration",
  [sym_variable_assignment] = "variable_assignment",
  [sym_newline] = "newline",
  [sym_type] = "type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_type_list_repeat1] = "type_list_repeat1",
  [aux_sym_variable_assignment_repeat1] = "variable_assignment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_expression] = sym_expression,
  [anon_sym_CR] = anon_sym_CR,
  [anon_sym_LF] = anon_sym_LF,
  [sym_name] = sym_name,
  [anon_sym_s64] = anon_sym_s64,
  [anon_sym_f64] = anon_sym_f64,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym_result_list] = sym_result_list,
  [sym_type_list] = sym_type_list,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_variable_assignment] = sym_variable_assignment,
  [sym_newline] = sym_newline,
  [sym_type] = sym_type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_type_list_repeat1] = aux_sym_type_list_repeat1,
  [aux_sym_variable_assignment_repeat1] = aux_sym_variable_assignment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_CR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_s64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f64] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_result_list] = {
    .visible = true,
    .named = true,
  },
  [sym_type_list] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_assignment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_parameters = 2,
  field_result = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_result] = "result",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
    {field_parameters, 2},
  [2] =
    {field_name, 1},
    {field_parameters, 2},
    {field_result, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 16,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 17,
  [43] = 35,
  [44] = 16,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 21,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 52,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '(', 11,
        ')', 13,
        ',', 12,
        '/', 4,
        '1', 15,
        '=', 14,
        'f', 19,
        's', 20,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\r') ADVANCE(16);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '=') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(30);
      END_STATE();
    case 5:
      if (lookahead == '4') ADVANCE(29);
      END_STATE();
    case 6:
      if (lookahead == '4') ADVANCE(28);
      END_STATE();
    case 7:
      if (lookahead == '_') ADVANCE(8);
      if (lookahead == 'n') ADVANCE(21);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == '_') ADVANCE(8);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_function);
      if (lookahead == '_') ADVANCE(8);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_expression);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_CR);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\r') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\r') ADVANCE(16);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '6') ADVANCE(5);
      if (lookahead == 'u') ADVANCE(7);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '6') ADVANCE(6);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '_') ADVANCE(8);
      if (lookahead == 'c') ADVANCE(25);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '_') ADVANCE(8);
      if (lookahead == 'i') ADVANCE(24);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '_') ADVANCE(8);
      if (lookahead == 'n') ADVANCE(10);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '_') ADVANCE(8);
      if (lookahead == 'o') ADVANCE(23);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '_') ADVANCE(8);
      if (lookahead == 't') ADVANCE(22);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '_') ADVANCE(8);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_s64);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_f64);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_expression] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_s64] = ACTIONS(1),
    [anon_sym_f64] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(55),
    [sym__statement] = STATE(2),
    [sym_function_definition] = STATE(2),
    [sym_variable_declaration] = STATE(2),
    [sym_variable_assignment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_function] = ACTIONS(7),
    [sym_name] = ACTIONS(9),
    [sym_comment] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      sym_name,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym_comment,
    STATE(3), 5,
      sym__statement,
      sym_function_definition,
      sym_variable_declaration,
      sym_variable_assignment,
      aux_sym_source_file_repeat1,
  [20] = 5,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(22), 1,
      sym_name,
    ACTIONS(25), 1,
      sym_comment,
    STATE(3), 5,
      sym__statement,
      sym_function_definition,
      sym_variable_declaration,
      sym_variable_assignment,
      aux_sym_source_file_repeat1,
  [40] = 6,
    STATE(8), 1,
      sym_type,
    STATE(25), 1,
      sym_result_list,
    STATE(26), 1,
      sym_type_list,
    ACTIONS(28), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(30), 2,
      anon_sym_function,
      sym_name,
    ACTIONS(32), 2,
      anon_sym_s64,
      anon_sym_f64,
  [62] = 8,
    ACTIONS(34), 1,
      anon_sym_COMMA,
    ACTIONS(36), 1,
      anon_sym_EQ,
    ACTIONS(38), 1,
      anon_sym_CR,
    ACTIONS(40), 1,
      anon_sym_LF,
    ACTIONS(42), 1,
      sym_comment,
    STATE(10), 1,
      aux_sym_parameter_list_repeat1,
    STATE(22), 1,
      aux_sym_variable_assignment_repeat1,
    STATE(41), 1,
      sym_newline,
  [87] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(44), 1,
      anon_sym_COMMA,
    ACTIONS(46), 1,
      anon_sym_EQ,
    STATE(5), 1,
      sym_type,
    STATE(38), 1,
      aux_sym_variable_assignment_repeat1,
    ACTIONS(48), 2,
      anon_sym_s64,
      anon_sym_f64,
  [107] = 4,
    ACTIONS(54), 1,
      anon_sym_COMMA,
    STATE(7), 1,
      aux_sym_type_list_repeat1,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(52), 2,
      anon_sym_function,
      sym_name,
  [122] = 4,
    ACTIONS(61), 1,
      anon_sym_COMMA,
    STATE(12), 1,
      aux_sym_type_list_repeat1,
    ACTIONS(57), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(59), 2,
      anon_sym_function,
      sym_name,
  [137] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(46), 1,
      sym_type,
    ACTIONS(63), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(65), 2,
      anon_sym_s64,
      anon_sym_f64,
  [152] = 6,
    ACTIONS(38), 1,
      anon_sym_CR,
    ACTIONS(40), 1,
      anon_sym_LF,
    ACTIONS(42), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      aux_sym_parameter_list_repeat1,
    STATE(27), 1,
      sym_newline,
  [171] = 2,
    ACTIONS(71), 2,
      anon_sym_function,
      sym_name,
    ACTIONS(69), 4,
      ts_builtin_sym_end,
      anon_sym_s64,
      anon_sym_f64,
      sym_comment,
  [182] = 4,
    ACTIONS(61), 1,
      anon_sym_COMMA,
    STATE(7), 1,
      aux_sym_type_list_repeat1,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(75), 2,
      anon_sym_function,
      sym_name,
  [197] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(19), 1,
      sym_type,
    ACTIONS(48), 2,
      anon_sym_s64,
      anon_sym_f64,
    ACTIONS(63), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
  [212] = 2,
    ACTIONS(79), 2,
      anon_sym_function,
      sym_name,
    ACTIONS(77), 4,
      ts_builtin_sym_end,
      anon_sym_s64,
      anon_sym_f64,
      sym_comment,
  [223] = 2,
    ACTIONS(83), 2,
      anon_sym_function,
      sym_name,
    ACTIONS(81), 4,
      ts_builtin_sym_end,
      anon_sym_s64,
      anon_sym_f64,
      sym_comment,
  [234] = 2,
    ACTIONS(42), 1,
      sym_comment,
    ACTIONS(85), 4,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_CR,
      anon_sym_LF,
  [244] = 4,
    ACTIONS(42), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(90), 2,
      anon_sym_CR,
      anon_sym_LF,
  [258] = 2,
    ACTIONS(52), 2,
      anon_sym_function,
      sym_name,
    ACTIONS(50), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym_comment,
  [268] = 4,
    ACTIONS(42), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_COMMA,
    ACTIONS(95), 1,
      anon_sym_EQ,
    ACTIONS(97), 2,
      anon_sym_CR,
      anon_sym_LF,
  [282] = 2,
    ACTIONS(85), 2,
      anon_sym_function,
      sym_name,
    ACTIONS(99), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym_comment,
  [292] = 2,
    ACTIONS(42), 1,
      sym_comment,
    ACTIONS(97), 3,
      anon_sym_COMMA,
      anon_sym_CR,
      anon_sym_LF,
  [301] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(44), 1,
      anon_sym_COMMA,
    ACTIONS(101), 1,
      anon_sym_EQ,
    STATE(23), 1,
      aux_sym_variable_assignment_repeat1,
  [314] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      anon_sym_EQ,
    ACTIONS(103), 1,
      anon_sym_COMMA,
    STATE(23), 1,
      aux_sym_variable_assignment_repeat1,
  [327] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(28), 1,
      sym_type,
    ACTIONS(65), 2,
      anon_sym_s64,
      anon_sym_f64,
  [338] = 2,
    ACTIONS(106), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(108), 2,
      anon_sym_function,
      sym_name,
  [347] = 2,
    ACTIONS(110), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(112), 2,
      anon_sym_function,
      sym_name,
  [356] = 2,
    ACTIONS(114), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(116), 2,
      anon_sym_function,
      sym_name,
  [365] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    ACTIONS(120), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      aux_sym_parameter_list_repeat1,
  [378] = 2,
    ACTIONS(122), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(124), 2,
      anon_sym_function,
      sym_name,
  [387] = 2,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(128), 2,
      anon_sym_function,
      sym_name,
  [396] = 4,
    ACTIONS(38), 1,
      anon_sym_CR,
    ACTIONS(40), 1,
      anon_sym_LF,
    ACTIONS(42), 1,
      sym_comment,
    STATE(34), 1,
      sym_newline,
  [409] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(18), 1,
      sym_type,
    ACTIONS(32), 2,
      anon_sym_s64,
      anon_sym_f64,
  [420] = 4,
    ACTIONS(38), 1,
      anon_sym_CR,
    ACTIONS(40), 1,
      anon_sym_LF,
    ACTIONS(42), 1,
      sym_comment,
    STATE(29), 1,
      sym_newline,
  [433] = 2,
    ACTIONS(130), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(132), 2,
      anon_sym_function,
      sym_name,
  [442] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(21), 1,
      sym_type,
    ACTIONS(48), 2,
      anon_sym_s64,
      anon_sym_f64,
  [453] = 4,
    ACTIONS(38), 1,
      anon_sym_CR,
    ACTIONS(40), 1,
      anon_sym_LF,
    ACTIONS(42), 1,
      sym_comment,
    STATE(39), 1,
      sym_newline,
  [466] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    ACTIONS(134), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_parameter_list_repeat1,
  [479] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(44), 1,
      anon_sym_COMMA,
    ACTIONS(136), 1,
      anon_sym_EQ,
    STATE(23), 1,
      aux_sym_variable_assignment_repeat1,
  [492] = 2,
    ACTIONS(138), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(140), 2,
      anon_sym_function,
      sym_name,
  [501] = 2,
    ACTIONS(142), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(144), 2,
      anon_sym_function,
      sym_name,
  [510] = 2,
    ACTIONS(146), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(148), 2,
      anon_sym_function,
      sym_name,
  [519] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(153), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_parameter_list_repeat1,
  [532] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(48), 1,
      sym_type,
    ACTIONS(65), 2,
      anon_sym_s64,
      anon_sym_f64,
  [543] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [552] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_LPAREN,
    STATE(4), 1,
      sym_parameter_list,
  [562] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
  [570] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
    ACTIONS(161), 1,
      sym_name,
  [580] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [588] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym_expression,
  [595] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      sym_name,
  [602] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      sym_expression,
  [609] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      sym_name,
  [616] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym_name,
  [623] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      sym_expression,
  [630] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      ts_builtin_sym_end,
  [637] = 2,
    ACTIONS(42), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_LF,
  [644] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      sym_name,
  [651] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      sym_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 40,
  [SMALL_STATE(5)] = 62,
  [SMALL_STATE(6)] = 87,
  [SMALL_STATE(7)] = 107,
  [SMALL_STATE(8)] = 122,
  [SMALL_STATE(9)] = 137,
  [SMALL_STATE(10)] = 152,
  [SMALL_STATE(11)] = 171,
  [SMALL_STATE(12)] = 182,
  [SMALL_STATE(13)] = 197,
  [SMALL_STATE(14)] = 212,
  [SMALL_STATE(15)] = 223,
  [SMALL_STATE(16)] = 234,
  [SMALL_STATE(17)] = 244,
  [SMALL_STATE(18)] = 258,
  [SMALL_STATE(19)] = 268,
  [SMALL_STATE(20)] = 282,
  [SMALL_STATE(21)] = 292,
  [SMALL_STATE(22)] = 301,
  [SMALL_STATE(23)] = 314,
  [SMALL_STATE(24)] = 327,
  [SMALL_STATE(25)] = 338,
  [SMALL_STATE(26)] = 347,
  [SMALL_STATE(27)] = 356,
  [SMALL_STATE(28)] = 365,
  [SMALL_STATE(29)] = 378,
  [SMALL_STATE(30)] = 387,
  [SMALL_STATE(31)] = 396,
  [SMALL_STATE(32)] = 409,
  [SMALL_STATE(33)] = 420,
  [SMALL_STATE(34)] = 433,
  [SMALL_STATE(35)] = 442,
  [SMALL_STATE(36)] = 453,
  [SMALL_STATE(37)] = 466,
  [SMALL_STATE(38)] = 479,
  [SMALL_STATE(39)] = 492,
  [SMALL_STATE(40)] = 501,
  [SMALL_STATE(41)] = 510,
  [SMALL_STATE(42)] = 519,
  [SMALL_STATE(43)] = 532,
  [SMALL_STATE(44)] = 543,
  [SMALL_STATE(45)] = 552,
  [SMALL_STATE(46)] = 562,
  [SMALL_STATE(47)] = 570,
  [SMALL_STATE(48)] = 580,
  [SMALL_STATE(49)] = 588,
  [SMALL_STATE(50)] = 595,
  [SMALL_STATE(51)] = 602,
  [SMALL_STATE(52)] = 609,
  [SMALL_STATE(53)] = 616,
  [SMALL_STATE(54)] = 623,
  [SMALL_STATE(55)] = 630,
  [SMALL_STATE(56)] = 637,
  [SMALL_STATE(57)] = 644,
  [SMALL_STATE(58)] = 651,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3, 0, 1),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 3, 0, 1),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [34] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_list_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_type_list_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_list_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_list, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_list, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_assignment_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_list, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_list, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 5, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 5, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_parameter_list_repeat1, 3, 0, 0), REDUCE(aux_sym_variable_assignment_repeat1, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_variable_assignment_repeat1, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_parameter_list_repeat1, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_assignment_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, 0, 2),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4, 0, 2),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_result_list, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_result_list, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 4, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_assignment, 4, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_assignment, 4, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_newline, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_newline, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_assignment, 5, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_assignment, 5, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_assignment, 6, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_assignment, 6, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_newline, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_newline, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 3, 0, 0),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_assignment_repeat1, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [177] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_we(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "we",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
